adds completed exercise 7 (with minor amend to getArticleComments fr…
aBCodes23/nc-news pull request #6
Opened 2023-08-16 11:23 UTC by aBCodes23

…om task 6

2023-08-16 11:29 UTC, MRombi requested changes
Great job here, you are very close! Please add the tests I mentioned and resubmit 🙂 Let me know if you have any question 🙂

2023-08-16 11:29 UTC, MRombi commented on __tests__/app.test.js
> +    })
We should add a test for when the username is not valid 404 🙂

2023-08-16 11:29 UTC, MRombi commented on __tests__/app.test.js
> +  });
We should add a test for when there are unnecessary properties in the comment I.E. {fruit: 'apple', username: 'butter_bridge', body: 'this is a comment'}. We want to ignore the extra keys and send back 201 and the comment 🙂

2023-08-17 07:45 UTC, johnhutcheon approved these changes
Thanks for making the changes Alex, all good to merge!

2023-08-17 07:46 UTC, merged